const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();
const fs = require("fs");

const createCities = async () => {
  try {
    const citiesData = [
      { id: 17, name: "Badung" },
      { id: 18, name: "Balangan" },
      { id: 19, name: "Balikpapan" },
      { id: 20, name: "Banda Aceh" },
      { id: 21, name: "Bandar Lampung" },
      { id: 22, name: "Bandung" },
      { id: 23, name: "Bandung" },
      { id: 24, name: "Bandung Barat" },
      { id: 25, name: "Banggai" },
      { id: 26, name: "Banggai Kepulauan" },
      { id: 151, name: "Jakarta Barat" },
      { id: 152, name: "Jakarta Pusat" },
      { id: 153, name: "Jakarta Selatan" },
      { id: 154, name: "Jakarta Timur" },
      { id: 155, name: "Jakarta Utara" },
      { id: 156, name: "Jambi" },
      { id: 157, name: "Jayapura" },
      { id: 158, name: "Jayapura" },
      { id: 159, name: "Jayawijaya" },
      { id: 160, name: "Jember" },
      { id: 161, name: "Jembrana" },
      { id: 162, name: "Jeneponto" },
      { id: 163, name: "Jepara" },
      { id: 164, name: "Jombang" },
      { id: 165, name: "Kaimana" },
      { id: 166, name: "Kampar" },
      { id: 167, name: "Kapuas" },
      { id: 168, name: "Kapuas Hulu" },
      { id: 169, name: "Karanganyar" },
      { id: 170, name: "Karangasem" },
      { id: 171, name: "Karawang" },
      { id: 172, name: "Karimun" },
      { id: 173, name: "Karo" },
      { id: 174, name: "Katingan" },
      { id: 175, name: "Kaur" },
      { id: 176, name: "Kayong Utara" },
      { id: 177, name: "Kebumen" },
      { id: 178, name: "Kediri" },
      { id: 179, name: "Kediri" },
      { id: 180, name: "Keerom" },
      { id: 181, name: "Kendal" },
      { id: 182, name: "Kendari" },
      { id: 183, name: "Kepahiang" },
      { id: 184, name: "Kepulauan Anambas" },
      { id: 185, name: "Kepulauan Aru" },
      { id: 186, name: "Kepulauan Mentawai" },
      { id: 187, name: "Kepulauan Meranti" },
      { id: 188, name: "Kepulauan Sangihe" },
      { id: 189, name: "Kepulauan Seribu" },
      { id: 190, name: "Kepulauan Siau Tagulandang Biaro (Sitaro)" },
      { id: 191, name: "Kepulauan Sula" },
      { id: 192, name: "Kepulauan Talaud" },
      { id: 193, name: "Kepulauan Yapen (Yapen Waropen)" },
      { id: 194, name: "Kerinci" },
      { id: 195, name: "Ketapang" },
      { id: 196, name: "Klaten" },
      { id: 197, name: "Klungkung" },
      { id: 198, name: "Kolaka" },
      { id: 199, name: "Kolaka Utara" },
      { id: 200, name: "Konawe" },
      { id: 201, name: "Konawe Selatan" },
      { id: 202, name: "Konawe Utara" },
      { id: 203, name: "Kotabaru" },
      { id: 204, name: "Kotamobagu" },
      { id: 205, name: "Kotawaringin Barat" },
      { id: 206, name: "Kotawaringin Timur" },
      { id: 207, name: "Kuantan Singingi" },
      { id: 208, name: "Kubu Raya" },
      { id: 209, name: "Kudus" },
      { id: 210, name: "Kulon Progo" },
      { id: 211, name: "Kuningan" },
      { id: 212, name: "Kupang" },
      { id: 213, name: "Kupang" },
      { id: 214, name: "Kutai Barat" },
      { id: 215, name: "Kutai Kartanegara" },
      { id: 216, name: "Kutai Timur" },
      { id: 217, name: "Labuhan Batu" },
      { id: 218, name: "Labuhan Batu Selatan" },
      { id: 219, name: "Labuhan Batu Utara" },
      { id: 220, name: "Lahat" },
      { id: 221, name: "Lamandau" },
      { id: 222, name: "Lamongan" },
      { id: 223, name: "Lampung Barat" },
      { id: 224, name: "Lampung Selatan" },
      { id: 225, name: "Lampung Tengah" },
      { id: 226, name: "Lampung Timur" },
      { id: 227, name: "Lampung Utara" },
      { id: 228, name: "Landak" },
      { id: 229, name: "Langkat" },
      { id: 230, name: "Langsa" },
      { id: 231, name: "Lanny Jaya" },
      { id: 232, name: "Lebak" },
      { id: 233, name: "Lebong" },
      { id: 234, name: "Lembata" },
      { id: 235, name: "Lhokseumawe" },
      { id: 236, name: "Lima Puluh Koto/Kota" },
      { id: 237, name: "Lingga" },
      { id: 238, name: "Lombok Barat" },
      { id: 239, name: "Lombok Tengah" },
      { id: 240, name: "Lombok Timur" },
      { id: 241, name: "Lombok Utara" },
      { id: 242, name: "Lubuk Linggau" },
      { id: 243, name: "Lumajang" },
      { id: 244, name: "Luwu" },
      { id: 245, name: "Luwu Timur" },
      { id: 246, name: "Luwu Utara" },
      { id: 247, name: "Madiun" },
      { id: 248, name: "Madiun" },
      { id: 249, name: "Magelang" },
      { id: 250, name: "Magelang" },
      { id: 251, name: "Magetan" },
      { id: 252, name: "Majalengka" },
      { id: 253, name: "Majene" },
      { id: 254, name: "Makassar" },
      { id: 255, name: "Malang" },
      { id: 256, name: "Malang" },
      { id: 257, name: "Malinau" },
      { id: 258, name: "Maluku Barat Daya" },
      { id: 259, name: "Maluku Tengah" },
      { id: 260, name: "Maluku Tenggara" },
      { id: 261, name: "Maluku Tenggara Barat" },
      { id: 262, name: "Mamasa" },
      { id: 263, name: "Mamberamo Raya" },
      { id: 264, name: "Mamberamo Tengah" },
      { id: 265, name: "Mamuju" },
      { id: 266, name: "Mamuju Utara" },
      { id: 267, name: "Manado" },
      { id: 268, name: "Mandailing Natal" },
      { id: 269, name: "Manggarai" },
      { id: 270, name: "Manggarai Barat" },
      { id: 271, name: "Manggarai Timur" },
      { id: 272, name: "Manokwari" },
      { id: 273, name: "Manokwari Selatan" },
      { id: 274, name: "Mappi" },
      { id: 275, name: "Maros" },
      { id: 276, name: "Mataram" },
      { id: 277, name: "Maybrat" },
      { id: 278, name: "Medan" },
      { id: 306, name: "Ngawi" },
      { id: 307, name: "Nias" },
      { id: 308, name: "Nias Barat" },
      { id: 309, name: "Nias Selatan" },
      { id: 310, name: "Nias Utara" },
      { id: 311, name: "Nunukan" },
      { id: 312, name: "Ogan Ilir" },
      { id: 313, name: "Ogan Komering Ilir" },
      { id: 314, name: "Ogan Komering Ulu" },
      { id: 315, name: "Ogan Komering Ulu Selatan" },
      { id: 316, name: "Ogan Komering Ulu Timur" },
      { id: 317, name: "Pacitan" },
      { id: 318, name: "Padang" },
      { id: 319, name: "Padang Lawas" },
      { id: 320, name: "Padang Lawas Utara" },
      { id: 321, name: "Padang Panjang" },
      { id: 322, name: "Padang Pariaman" },
      { id: 323, name: "Padang Sidempuan" },
      { id: 324, name: "Pagar Alam" },
      { id: 325, name: "Pakpak Bharat" },
      { id: 326, name: "Palangka Raya" },
      { id: 327, name: "Palembang" },
      { id: 328, name: "Palopo" },
      { id: 329, name: "Palu" },
      { id: 330, name: "Pamekasan" },
      { id: 331, name: "Pandeglang" },
      { id: 332, name: "Pangandaran" },
      { id: 333, name: "Pangkajene Kepulauan" },
      { id: 334, name: "Pangkal Pinang" },
      { id: 335, name: "Paniai" },
      { id: 358, name: "Pidie" },
      { id: 359, name: "Pidie Jaya" },
      { id: 360, name: "Pinrang" },
      { id: 361, name: "Pohuwato" },
      { id: 362, name: "Polewali Mandar" },
      { id: 363, name: "Ponorogo" },
      { id: 364, name: "Pontianak" },
      { id: 365, name: "Pontianak" },
      { id: 366, name: "Poso" },
      { id: 367, name: "Prabumulih" },
      { id: 368, name: "Pringsewu" },
      { id: 369, name: "Probolinggo" },
      { id: 370, name: "Probolinggo" },
      { id: 371, name: "Pulang Pisau" },
      { id: 372, name: "Pulau Morotai" },
      { id: 373, name: "Puncak" },
      { id: 397, name: "Seluma" },
      { id: 398, name: "Semarang" },
      { id: 399, name: "Semarang" },
      { id: 400, name: "Seram Bagian Barat" },
      { id: 401, name: "Seram Bagian Timur" },
      { id: 402, name: "Serang" },
      { id: 403, name: "Serang" },
      { id: 404, name: "Serdang Bedagai" },
      { id: 405, name: "Seruyan" },
      { id: 406, name: "Siak" },
      { id: 407, name: "Sibolga" },
      { id: 408, name: "Sidenreng Rappang/Rapang" },
      { id: 409, name: "Sidoarjo" },
      { id: 410, name: "Sigi" },
      { id: 411, name: "Sijunjung (Sawah Lunto Sijunjung)" },
      { id: 412, name: "Sikka" },
      { id: 413, name: "Simalungun" },
      { id: 414, name: "Simeulue" },
      { id: 415, name: "Singkawang" },
      { id: 416, name: "Sinjai" },
      { id: 417, name: "Sintang" },
      { id: 418, name: "Situbondo" },
      { id: 419, name: "Sleman" },
      { id: 420, name: "Solok" },
      { id: 421, name: "Solok" },
      { id: 422, name: "Solok Selatan" },
      { id: 423, name: "Soppeng" },
      { id: 424, name: "Sorong" },
      { id: 425, name: "Sorong" },
      { id: 426, name: "Sorong Selatan" },
      { id: 427, name: "Sragen" },
      { id: 428, name: "Subang" },
      { id: 429, name: "Subulussalam" },
      { id: 430, name: "Sukabumi" },
      { id: 431, name: "Sukabumi" },
      { id: 432, name: "Sukamara" },
      { id: 433, name: "Sukoharjo" },
      { id: 434, name: "Sumba Barat" },
      { id: 435, name: "Sumba Barat Daya" },
      { id: 436, name: "Sumba Tengah" },
      { id: 437, name: "Sumba Timur" },
      { id: 438, name: "Sumbawa" },
      { id: 439, name: "Sumbawa Barat" },
      { id: 440, name: "Sumedang" },
      { id: 441, name: "Sumenep" },
      { id: 442, name: "Sungaipenuh" },
      { id: 443, name: "Supiori" },
      { id: 444, name: "Surabaya" },
      { id: 445, name: "Surakarta (Solo)" },
      { id: 446, name: "Tabalong" },
      { id: 447, name: "Tabanan" },
      { id: 448, name: "Takalar" },
      { id: 449, name: "Tambrauw" },
      { id: 450, name: "Tana Tidung" },
      { id: 451, name: "Tana Toraja" },
      { id: 452, name: "Tanah Bumbu" },
      { id: 453, name: "Tanah Datar" },
      { id: 454, name: "Tanah Laut" },
      { id: 455, name: "Tangerang" },
      { id: 456, name: "Tangerang" },
      { id: 457, name: "Tangerang Selatan" },
      { id: 458, name: "Tanggamus" },
      { id: 459, name: "Tanjung Balai" },
      { id: 460, name: "Tanjung Jabung Barat" },
      { id: 461, name: "Tanjung Jabung Timur" },
      { id: 462, name: "Tanjung Pinang" },
      { id: 501, name: "Yogyakarta" },
    ];

    for (const cityData of citiesData) {
      const { id, name } = cityData;

      await prisma.city.create({
        data: {
          id,
          name,
        },
      });
    }

    console.log("Cities created successfully!");
  } catch (error) {
    console.error("Error:", error);
  }
};

createCities();
async function main() {
  const topCategory = await prisma.category.create({
    data: {
      name: "Top",
      SubCategory: {
        createMany: {
          data: [
            { name: "T-shirt Long Sleeve" },
            { name: "T-shirt Short Sleeve" },
            { name: "Sweater" },
            { name: "Shirt Long Sleeve" },
            { name: "Shirt Short Sleeve" },
          ],
        },
      },
    },
    include: {
      SubCategory: true,
    },
  });

  const bottomCategory = await prisma.category.create({
    data: {
      name: "Bottom",
      SubCategory: {
        createMany: {
          data: [{ name: "Jeans" }, { name: "Sweatpants" }, { name: "Shorts" }],
        },
      },
    },
    include: {
      SubCategory: true,
    },
  });

  const outerwearCategory = await prisma.category.create({
    data: {
      name: "Outerwear",
      SubCategory: {
        createMany: {
          data: [{ name: "Jacket" }, { name: "Hoodie" }],
        },
      },
    },
    include: {
      SubCategory: true,
    },
  });

  await prisma.product.createMany({
    data: [
      {
        name: "Long Sleeve T-shirt",
        SKU: "LS1001",
        description: "Comfortable long sleeve t-shirt for all occasions.",
        slug: "long-sleeve-t-shirt",
        keyword: "t-shirt, long sleeve",
        category_id: 1,
        sub_category_id: 1,
      },
      {
        name: "Short Sleeve T-shirt",
        SKU: "SS1002",
        description: "Classic short sleeve t-shirt in various colors.",
        slug: "short-sleeve-t-shirt",
        keyword: "t-shirt, short sleeve",
        category_id: 1,
        sub_category_id: 2,
      },
      {
        name: "Sweater",
        SKU: "SW1003",
        description: "Warm and stylish sweater for chilly days.",
        slug: "sweater",
        keyword: "sweater",
        category_id: 1,
        sub_category_id: 3,
      },
      {
        name: "Jeans",
        SKU: "JE1004",
        description: "Durable denim jeans for everyday wear.",
        slug: "jeans",
        keyword: "jeans",
        category_id: 2,
        sub_category_id: 6,
      },
      {
        name: "Sweatpants",
        SKU: "SP1005",
        description: "Comfortable sweatpants for lounging or exercising.",
        slug: "sweatpants",
        keyword: "sweatpants",
        category_id: 2,
        sub_category_id: 7,
      },
      {
        name: "Shorts",
        SKU: "SH1006",
        description: "Casual shorts for warm weather.",
        slug: "shorts",
        keyword: "shorts",
        category_id: 2,
        sub_category_id: 8,
      },
      {
        name: "Jacket",
        SKU: "JA1007",
        description: "Stylish jacket for all seasons.",
        slug: "jacket",
        keyword: "jacket",
        category_id: 3,
        sub_category_id: 9,
      },
      {
        name: "Hoodie",
        SKU: "HD1008",
        description: "Cozy hoodie with a front pocket.",
        slug: "hoodie",
        keyword: "hoodie",
        category_id: 3,
        sub_category_id: 10,
      },
      // Add more products as needed
    ],
  });

  await prisma.productDetails.createMany({
    data: [
      {
        product_id: 1,
        color: "black",
        size: "S",
        stock: 50,
        price: 100000,
      },
      {
        product_id: 1,
        color: "black",
        size: "M",
        stock: 50,
        price: 100000,
      },
      {
        product_id: 1,
        color: "black",
        size: "L",
        stock: 50,
        price: 100000,
      },
      {
        product_id: 1,
        color: "black",
        size: "XL",
        stock: 50,
        price: 110000,
      },
      {
        product_id: 1,
        color: "white",
        size: "S",
        stock: 50,
        price: 100000,
      },
      {
        product_id: 1,
        color: "white",
        size: "M",
        stock: 50,
        price: 100000,
      },
      {
        product_id: 1,
        color: "white",
        size: "L",
        stock: 50,
        price: 100000,
      },
      {
        product_id: 1,
        color: "white",
        size: "XL",
        stock: 50,
        price: 110000,
      },
      {
        product_id: 2,
        color: "black",
        size: "S",
        stock: 60,
        price: 90000,
      },
      {
        product_id: 2,
        color: "black",
        size: "M",
        stock: 60,
        price: 90000,
      },
      {
        product_id: 2,
        color: "black",
        size: "L",
        stock: 60,
        price: 90000,
      },
      {
        product_id: 2,
        color: "black",
        size: "XL",
        stock: 60,
        price: 95000,
      },
      {
        product_id: 2,
        color: "white",
        size: "S",
        stock: 60,
        price: 90000,
      },
      {
        product_id: 2,
        color: "white",
        size: "M",
        stock: 60,
        price: 90000,
      },
      {
        product_id: 2,
        color: "white",
        size: "L",
        stock: 60,
        price: 90000,
      },
      {
        product_id: 2,
        color: "white",
        size: "XL",
        stock: 60,
        price: 95000,
      },
      {
        product_id: 3,
        color: "black",
        size: "S",
        stock: 40,
        price: 120000,
      },
      {
        product_id: 3,
        color: "black",
        size: "M",
        stock: 40,
        price: 120000,
      },
      {
        product_id: 3,
        color: "black",
        size: "L",
        stock: 40,
        price: 120000,
      },
      {
        product_id: 3,
        color: "black",
        size: "XL",
        stock: 40,
        price: 130000,
      },
      {
        product_id: 3,
        color: "white",
        size: "S",
        stock: 40,
        price: 120000,
      },
      {
        product_id: 3,
        color: "white",
        size: "M",
        stock: 40,
        price: 120000,
      },
      {
        product_id: 3,
        color: "white",
        size: "L",
        stock: 40,
        price: 120000,
      },
      {
        product_id: 3,
        color: "white",
        size: "XL",
        stock: 40,
        price: 130000,
      },
      {
        product_id: 4,
        color: "blue",
        size: "S",
        stock: 30,
        price: 80000,
      },
      {
        product_id: 4,
        color: "blue",
        size: "M",
        stock: 30,
        price: 80000,
      },
      {
        product_id: 4,
        color: "blue",
        size: "L",
        stock: 30,
        price: 80000,
      },
      {
        product_id: 4,
        color: "blue",
        size: "XL",
        stock: 30,
        price: 85000,
      },
      {
        product_id: 4,
        color: "red",
        size: "S",
        stock: 30,
        price: 80000,
      },
      {
        product_id: 4,
        color: "red",
        size: "M",
        stock: 30,
        price: 80000,
      },
      {
        product_id: 4,
        color: "red",
        size: "L",
        stock: 30,
        price: 80000,
      },
      {
        product_id: 4,
        color: "red",
        size: "XL",
        stock: 30,
        price: 85000,
      },
      {
        product_id: 5,
        color: "black",
        size: "S",
        stock: 45,
        price: 110000,
      },
      {
        product_id: 5,
        color: "black",
        size: "M",
        stock: 45,
        price: 110000,
      },
      {
        product_id: 5,
        color: "black",
        size: "L",
        stock: 45,
        price: 110000,
      },
      {
        product_id: 5,
        color: "black",
        size: "XL",
        stock: 45,
        price: 120000,
      },
      {
        product_id: 5,
        color: "white",
        size: "S",
        stock: 45,
        price: 110000,
      },
      {
        product_id: 5,
        color: "white",
        size: "M",
        stock: 45,
        price: 110000,
      },
      {
        product_id: 5,
        color: "white",
        size: "L",
        stock: 45,
        price: 110000,
      },
      {
        product_id: 5,
        color: "white",
        size: "XL",
        stock: 45,
        price: 120000,
      },
      {
        product_id: 6,
        color: "blue",
        size: "S",
        stock: 55,
        price: 95000,
      },
      {
        product_id: 6,
        color: "blue",
        size: "M",
        stock: 55,
        price: 95000,
      },
      {
        product_id: 6,
        color: "blue",
        size: "L",
        stock: 55,
        price: 95000,
      },
      {
        product_id: 6,
        color: "blue",
        size: "XL",
        stock: 55,
        price: 100000,
      },
      {
        product_id: 6,
        color: "black",
        size: "S",
        stock: 55,
        price: 95000,
      },
      {
        product_id: 6,
        color: "black",
        size: "M",
        stock: 55,
        price: 95000,
      },
      {
        product_id: 6,
        color: "black",
        size: "L",
        stock: 55,
        price: 95000,
      },
      {
        product_id: 6,
        color: "black",
        size: "XL",
        stock: 55,
        price: 100000,
      },
      {
        product_id: 7,
        color: "red",
        size: "S",
        stock: 65,
        price: 85000,
      },
      {
        product_id: 7,
        color: "red",
        size: "M",
        stock: 65,
        price: 85000,
      },
      {
        product_id: 7,
        color: "red",
        size: "L",
        stock: 65,
        price: 85000,
      },
      {
        product_id: 7,
        color: "red",
        size: "XL",
        stock: 65,
        price: 90000,
      },
      {
        product_id: 7,
        color: "blue",
        size: "S",
        stock: 65,
        price: 85000,
      },
      {
        product_id: 7,
        color: "blue",
        size: "M",
        stock: 65,
        price: 85000,
      },
      {
        product_id: 7,
        color: "blue",
        size: "L",
        stock: 65,
        price: 85000,
      },
      {
        product_id: 7,
        color: "blue",
        size: "XL",
        stock: 65,
        price: 90000,
      },
      {
        product_id: 8,
        color: "green",
        size: "S",
        stock: 35,
        price: 130000,
      },
      {
        product_id: 8,
        color: "green",
        size: "M",
        stock: 35,
        price: 130000,
      },
      {
        product_id: 8,
        color: "green",
        size: "L",
        stock: 35,
        price: 130000,
      },
      {
        product_id: 8,
        color: "green",
        size: "XL",
        stock: 35,
        price: 140000,
      },
      {
        product_id: 8,
        color: "black",
        size: "S",
        stock: 35,
        price: 130000,
      },
      {
        product_id: 8,
        color: "black",
        size: "M",
        stock: 35,
        price: 130000,
      },
      {
        product_id: 8,
        color: "black",
        size: "L",
        stock: 35,
        price: 130000,
      },
      {
        product_id: 8,
        color: "black",
        size: "XL",
        stock: 35,
        price: 140000,
      },
    ],
  });

  await prisma.productGallery.createMany({
    data: [
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Long-Sleeve-T-shirt-1.jpg?alt=media&token=08cf6582-96ac-48d2-8096-4ea0f1badc53&_gl=1*1tg41jv*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTM1Ni42LjAuMA..",
        product_id: 1,
      },
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Long-Sleeve-T-shirt-2.jpg?alt=media&token=8e452632-2020-4b32-8122-b0d1e8ce1a37&_gl=1*i5n6rg*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTM3MC42MC4wLjA.",
        product_id: 1,
      },
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Short-Sleeve-T-shirt-1.jpg?alt=media&token=8ad38e1b-158c-48b8-90d8-76c8e8d4dcd0&_gl=1*13wryaq*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTM4Ni40NC4wLjA.",
        product_id: 2,
      },
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Short-Sleeve-T-shirt-2.jpg?alt=media&token=3dc697da-8283-48a1-b4e9-16299383c17e&_gl=1*a579ry*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTQwNi4yNC4wLjA.",
        product_id: 2,
      },
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Sweater-1.jpg?alt=media&token=bce127a1-b64e-4365-815d-5727583e26ee&_gl=1*fsnxq4*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTQxNy4xMy4wLjA.",
        product_id: 3,
      },
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Sweater-2.jpg?alt=media&token=26f94c65-dbf0-4ec5-b35f-b90f096066a4&_gl=1*1xu9tdq*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTQyNi40LjAuMA..",
        product_id: 3,
      },
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Jeans-1.jpg?alt=media&token=2911b0b9-a114-423b-878a-ec3af8bb38b1&_gl=1*i7sqo4*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTQ0Mi42MC4wLjA.",
        product_id: 4,
      },
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Jeans-2.jpg?alt=media&token=a1cd76f6-6c64-4c75-82e1-0e3d90a2b46b&_gl=1*myuhne*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTQ0OS41My4wLjA.",
        product_id: 4,
      },
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Sweatpants-1.jpg?alt=media&token=ed759e4a-7540-4711-a5a1-cb7689d65b15&_gl=1*tqyoer*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTQ2Mi40MC4wLjA.",
        product_id: 5,
      },
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Sweatpants-2.jpg?alt=media&token=ae9e9304-212e-45d9-bec5-2964910d0b45&_gl=1*15daj2s*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTQ3NC4yOC4wLjA.",
        product_id: 5,
      },
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Shorts-1.jpg?alt=media&token=d425cd72-5f18-477f-bb6b-3bae2e0f7415&_gl=1*14c3rye*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTQ4NS4xNy4wLjA.",
        product_id: 6,
      },
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Shorts-2.jpg?alt=media&token=5558b23a-617f-41cf-b61e-5ec955aeb4b5&_gl=1*c065ts*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTQ5My45LjAuMA..",
        product_id: 6,
      },
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Jacket-1.jpg?alt=media&token=5ab58c9b-8d93-4736-9b4d-70ca54b1f7e3&_gl=1*wegvsq*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTUwOC42MC4wLjA.",
        product_id: 7,
      },
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Jacket-2.jpg?alt=media&token=865713c7-3471-4f41-895d-b6c398d6a85d&_gl=1*1i5xsi0*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTUyMy40NS4wLjA.",
        product_id: 7,
      },
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Hoodie-1.jpg?alt=media&token=47c634c3-f1dc-47d3-ac1b-9dc95d29a597&_gl=1*gas7ku*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTUzMS4zNy4wLjA.",
        product_id: 8,
      },
      {
        photo:
          "https://firebasestorage.googleapis.com/v0/b/sukses-abadi.appspot.com/o/Hoodie-2.jpg?alt=media&token=d4fe77c2-7ca7-425f-8824-d08963f0230b&_gl=1*k3j6mg*_ga*MTEwMTA5MjIyNS4xNjk3MjcwMjQ5*_ga_CW55HF8NVT*MTY5NzI5MTMwMi41LjEuMTY5NzI5MTUzOS4yOS4wLjA.",
        product_id: 8,
      },
    ],
  });

  await prisma.admin.createMany({
    data: [
      {
        username: "admin1",
        password:
          "$2b$10$QLkE0KoIcpoXwQpTw1o94OrwDBM0XCr5Q/C2XVNx6zoexCUAPn.eG",
        address: "123 Admin St",
      },
      {
        username: "admin2",
        password:
          "$2b$10$ItfEtkGdU7GoB4800m3JgO7mHZ2MK.YkAGnyHNFNTJ8JFM.m9gepm",
        address: "456 Admin Rd",
      },
    ],
  });

  await prisma.bankAccount.createMany({
    data: [
      {
        account_holder: "-",
        bank_name: "CreditCard",
        account_number: "-",
        admin_id: 1,
      },
      {
        account_holder: "Admin 1",
        bank_name: "BSI",
        account_number: "1234567890",
        admin_id: 1,
      },
      {
        account_holder: "Admin 1",
        bank_name: "BCA",
        account_number: "9876543210",
        admin_id: 1,
      },
      {
        account_holder: "Admin 1",
        bank_name: "BNI",
        account_number: "5678901234",
        admin_id: 1,
      },
      {
        account_holder: "Admin 2",
        bank_name: "BRI",
        account_number: "5432109876",
        admin_id: 2,
      },
      {
        account_holder: "Admin 2",
        bank_name: "Mandiri",
        account_number: "7890123456",
        admin_id: 2,
      },
      {
        account_holder: "Admin 2",
        bank_name: "Permata",
        account_number: "2345678901",
        admin_id: 2,
      },
    ],
  });

  console.log("Seed data created successfully.");
}

main()
  .then(createCities())
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
